### ISSUE TITLE
이메일 인증 URL이 localhost입니다

### ISSUE THREAD

**Issue by ChangJoo-Park** [shwang0416/flashcards#1]
`https://pdatbbrfgvjyhppdvyfp.supabase.co/auth/v1/verify?token=pkce_a30029ec2517c5ba2c6e4c8851026806a7fa2d0b91a2f7d2fa2806a1&type=signup&redirect_to=http://localhost:3000`

redirect_to 확인해주셔요

**Comment by shwang0416** [comment]
덕분에 확인하고 c5ae5db으로 수정되었습니다! 감사합니다🫂
